### ISSUE TITLE
Scaling of the landing page

### ISSUE THREAD

**Issue by vitalysk** [TLL-co/urbalytics-fe#2]
Need to adjust scaling to work on mobile and ipad-size. Currently, esp. mobile scaling does not work properly
@tan-c

**Comment by vitalysk** [comment]
- [ ] Mockup for iPhone (VS)
- [ ] Mockup for iPad (VS)

**Comment by vitalysk** [comment]
Here is the mockup for iPhone: https://www.figma.com/file/klQmRXEcStCF615cFkpVdK/Landing-iPhone-v1?node-id=0%3A1

**Comment by vitalysk** [comment]
Here is the mockup for iPad (vertical): https://www.figma.com/file/4pCRGzD6XGUC0AqBzaNPjA/Landing-iPad-Vertical-v1?node-id=0%3A1
Needs to be discussed

**Comment by tan-c** [comment]
As discussed, ipad view will be same as desktop, will fix iPhone view first

**Comment by tan-c** [comment]
implemtend in https://github.com/TLL-co/urbalytics-fe/commit/1f1ab8240e3939fff0e43d12211c55950c5204a7 for mobile
