### ISSUE TITLE
Landing page: Main text alignment

### ISSUE THREAD

**Issue by vitalysk** [TLL-co/urbalytics-fe#4]
Let's make sure that all elements of the main text are correctly aligned (like in Figma mockup)

![image](https://user-images.githubusercontent.com/13452584/120923174-747ee280-c6cd-11eb-8a25-2423d94cb643.png)

**Comment by tan-c** [comment]
@vitalysk do you see this as a fixed width or fixed % of screen?
If it is fixed width the it might look too small on the big screen, but if fixed % of screen then they wont along as the font size are different (see below)


![Screen Shot 2021-06-06 at 22 24 07](https://user-images.githubusercontent.com/2509485/120925971-ebd86480-c715-11eb-815e-5e1230a69612.png)
