### ISSUE TITLE
Landing page: Submit the email

### ISSUE THREAD

**Issue by vitalysk** [TLL-co/urbalytics-fe#6]
Button: No border, but should have small shadow around it:
background: #FFE156;
box-shadow: 0px 0px 5px 2px rgba(1, 41, 65, 0.2);
border-radius: 2px;

Line: same yellow as button (maybe 1-2 px thicker)
Add "ENTER YOUR EMAIL" text

**Comment by tan-c** [comment]
Updated but using a light gray for placeholder color

![Uploading Screen Shot 2021-06-06 at 22.24.39.png…]()
